#define _POSIX_C_SOURCE 200809L
#include "thread_confidence.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static const char *header = "timestamp,elapsed_ms,pid,start_time_ticks,app_id,entity_id,classification,classification_score,placement_relation,evidence_status\n";
static int write_file(const char *path, const char *rows) { FILE *f=fopen(path,"w"); return f && fputs(header,f)>=0 && fputs(rows,f)>=0 && fclose(f)==0; }
static int evaluate(const char *rows, pid_t tid, int valid, size_t count, const char *reason, ThreadConfidence *out) { char path[]="/tmp/tc-XXXXXX"; int fd=mkstemp(path), ok; if(fd<0)return 0; close(fd); if(!write_file(path,rows))return 0; ok=thread_confidence_evaluate(path,42,99,tid,out)==valid&&out->valid_sample_count==count&&!strcmp(out->reason,reason); unlink(path); return ok; }
static void report(const char *name,int ok,int *all) { printf("%s: %s\n",name,ok?"PASS":"FAIL"); *all&=ok; }
int main(void) { const char *h="t,1,42,99,a,101,HOT,1,REMOTE,MEASURED_REMOTE_THREAD_TO_MEMORY\n"; char two[512],three[768],five[1280],cold[768],local[768],tid[768],generation[768]; ThreadConfidence c; int all=1,ok; snprintf(two,sizeof(two),"%s%s",h,h); snprintf(three,sizeof(three),"%s%s%s",h,h,h); snprintf(five,sizeof(five),"%s%s%s%s%s",h,h,h,h,h); snprintf(cold,sizeof(cold),"%s%s%st,1,42,99,a,101,COLD,1,REMOTE,MEASURED_REMOTE_THREAD_TO_MEMORY\n",h,h,h); snprintf(local,sizeof(local),"%s%s%st,1,42,99,a,101,HOT,1,LOCAL,MEASURED_LOCAL_PLACEMENT\n",h,h,h); snprintf(tid,sizeof(tid),"%s%st,1,42,99,a,102,HOT,1,REMOTE,MEASURED_REMOTE_THREAD_TO_MEMORY\n",h,h); snprintf(generation,sizeof(generation),"%s%st,1,42,100,a,101,HOT,1,REMOTE,MEASURED_REMOTE_THREAD_TO_MEMORY\n",h,h); report("CF01_LATEST_THREE_HOT_REMOTE_SAME_TID",evaluate(three,101,1,3,"VALID",&c),&all); report("CF02_OLD_STREAK_NOT_ACCEPTED",evaluate(cold,101,0,0,"CLASS_CHANGED",&c),&all); report("CF03_ONLY_TWO_SAMPLES",evaluate(two,101,0,2,"INSUFFICIENT_SAMPLES",&c),&all); report("CF04_LOCAL_BREAKS_STREAK",evaluate(local,101,0,0,"PLACEMENT_NOT_REMOTE",&c),&all); report("CF05_TID_CHANGE_BREAKS_STREAK",evaluate(tid,102,0,1,"INSUFFICIENT_SAMPLES",&c),&all); report("CF06_GENERATION_CHANGE",evaluate(generation,101,0,0,"GENERATION_CHANGED",&c),&all); report("CF07_MALFORMED_REQUIRED_FIELD",evaluate("broken\n",101,0,0,"EVIDENCE_UNAVAILABLE",&c),&all); report("CF08_MORE_THAN_THREE",evaluate(five,101,1,5,"VALID",&c),&all); ok=evaluate(cold,101,0,0,"CLASS_CHANGED",&c)&&!strcmp(c.latest_classification,"COLD")&&!strcmp(c.latest_placement_relation,"REMOTE")&&!strcmp(c.reason,"CLASS_CHANGED"); report("CF09_DIAGNOSTIC_STRING_LIFETIME",ok,&all); { char cycle[]="/tmp/tcc-XXXXXX",history[]="/tmp/tch-XXXXXX"; int a=mkstemp(cycle),b=mkstemp(history); close(a);close(b); write_file(cycle,h); ok=thread_confidence_append(cycle,history,42,99,1)&&thread_confidence_append(cycle,history,42,99,1)&&thread_confidence_evaluate(history,42,99,101,&c)==0&&c.valid_sample_count==1&&thread_confidence_append(cycle,history,42,99,2)&&thread_confidence_append(cycle,history,42,99,3)&&thread_confidence_evaluate(history,42,99,101,&c)&&c.valid_sample_count==3&&thread_confidence_append(cycle,history,42,100,1); unlink(cycle);unlink(history); report("CF10_DUPLICATE_CYCLE_DOES_NOT_INFLATE_CONFIDENCE",ok,&all); } return all?EXIT_SUCCESS:EXIT_FAILURE; }
