#include "p5_thread_activity_calibration.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { uint64_t run; uint32_t worker; P5ThreadActivityProfile profile; double value; size_t windows; } unit_t;
static void reason(char *out, size_t size, const char *value) { if (out != NULL && size) snprintf(out, size, "%s", value); }
static bool text(const char *s) { return s != NULL && s[0] != '\0'; }
static bool same(const char *a, const char *b) { return text(a) && text(b) && strcmp(a, b) == 0; }
static bool placement(P5ThreadActivityPlacementMode value) { return value == P5_THREAD_ACTIVITY_PLACEMENT_LOCAL || value == P5_THREAD_ACTIVITY_PLACEMENT_REMOTE; }
static bool profile(P5ThreadActivityProfile value) { return value >= P5_THREAD_ACTIVITY_PROFILE_LOW && value <= P5_THREAD_ACTIVITY_PROFILE_HIGH; }
static int compare_double(const void *a, const void *b) { double x = *(const double *)a, y = *(const double *)b; return x < y ? -1 : x > y; }
static int compare_sample(const void *a, const void *b) { const P5ThreadActivityRawSample *x = a, *y = b; return x->sample_index < y->sample_index ? -1 : x->sample_index > y->sample_index; }
static double percentile(const double *v, size_t n, double p) { double r = p * (double)(n - 1); size_t l = (size_t)floor(r), u = (size_t)ceil(r); return v[l] + (r - (double)l) * (v[u] - v[l]); }
static void statistics(double *v, size_t n, P5ThreadActivityStatistics *s) { double sum = 0, sq = 0; qsort(v, n, sizeof(*v), compare_double); for (size_t i = 0; i < n; i++) sum += v[i]; s->count = n; s->min = v[0]; s->max = v[n - 1]; s->mean = sum / n; for (size_t i = 0; i < n; i++) { double d = v[i] - s->mean; sq += d * d; } s->median = percentile(v, n, .5); s->stddev = sqrt(sq / n); s->p10 = percentile(v, n, .1); s->p90 = percentile(v, n, .9); }
static bool context_shape(const P5ThreadActivityContext *c) { return c != NULL && c->schema_version == P5_THREAD_ACTIVITY_SCHEMA_VERSION && text(c->architecture) && text(c->cpu_vendor) && text(c->cpu_model_name) && c->online_cpu_count && c->numa_node_count && c->page_size && text(c->hardware_fingerprint) && same(c->metric_name, P5_THREAD_ACTIVITY_METRIC_NAME) && c->metric_version == P5_THREAD_ACTIVITY_METRIC_VERSION && same(c->metric_unit, P5_THREAD_ACTIVITY_METRIC_UNIT) && c->worker_count && c->memory_mb && placement(c->placement_mode) && text(c->benchmark_definition_version) && text(c->intensity_profile_version) && c->low_intensity_percent >= 1 && c->low_intensity_percent < c->mid_intensity_percent && c->mid_intensity_percent < c->high_intensity_percent && c->high_intensity_percent <= 100 && c->window_interval_count == P5_THREAD_ACTIVITY_WINDOW_INTERVALS && c->minimum_worker_run_units == P5_THREAD_ACTIVITY_MIN_WORKER_RUN_UNITS; }
static uint32_t intensity(const P5ThreadActivityContext *c, P5ThreadActivityProfile p) { return p == P5_THREAD_ACTIVITY_PROFILE_LOW ? c->low_intensity_percent : p == P5_THREAD_ACTIVITY_PROFILE_MID ? c->mid_intensity_percent : c->high_intensity_percent; }

const char *p5_thread_activity_profile_name(P5ThreadActivityProfile p) { return p == P5_THREAD_ACTIVITY_PROFILE_LOW ? "LOW" : p == P5_THREAD_ACTIVITY_PROFILE_MID ? "MID" : p == P5_THREAD_ACTIVITY_PROFILE_HIGH ? "HIGH" : "UNKNOWN"; }
const char *p5_thread_activity_class_name(P5ThreadActivityClass c) { return c == P5_THREAD_ACTIVITY_COLD ? "COLD" : c == P5_THREAD_ACTIVITY_MODERATE ? "MODERATE" : c == P5_THREAD_ACTIVITY_HOT ? "HOT" : "UNAVAILABLE"; }
const char *p5_thread_activity_calibration_status_name(P5ThreadActivityCalibrationStatus s) { return s == P5_THREAD_ACTIVITY_CALIBRATION_VALID ? "VALID" : s == P5_THREAD_ACTIVITY_CALIBRATION_NOT_SEPARABLE ? "NOT_SEPARABLE" : s == P5_THREAD_ACTIVITY_CALIBRATION_INSUFFICIENT_SAMPLES ? "INSUFFICIENT_SAMPLES" : s == P5_THREAD_ACTIVITY_CALIBRATION_INVALID_CONTEXT ? "INVALID_CONTEXT" : "MALFORMED"; }
bool p5_thread_activity_hardware_fingerprint(const P5ThreadActivityContext *c, char *out, size_t n) { int w; if (c == NULL || out == NULL || !n || !text(c->architecture) || !text(c->cpu_vendor) || !c->online_cpu_count || !c->numa_node_count || !c->page_size) return false; w = snprintf(out, n, "arch=%s|vendor=%s|family=%u|model=%u|cpus=%u|numa=%u|page=%llu", c->architecture, c->cpu_vendor, c->cpu_family, c->cpu_model, c->online_cpu_count, c->numa_node_count, (unsigned long long)c->page_size); return w >= 0 && (size_t)w < n; }
bool p5_thread_activity_rate(uint64_t delta, uint64_t interval, double *out) { double r; if (out == NULL || !interval) return false; r = (double)delta / interval; if (!isfinite(r)) return false; *out = r; return true; }
bool p5_thread_activity_calibration_context_matches(const P5ThreadActivityContext *a, const P5ThreadActivityContext *b, char *out, size_t n) {
    if (!context_shape(a) || !context_shape(b)) { reason(out, n, "invalid_context"); return false; }
#define M(f, s) if (a->f != b->f) { reason(out,n,s); return false; }
#define T(f, s) if (!same(a->f,b->f)) { reason(out,n,s); return false; }
    M(schema_version,"schema_version_mismatch"); T(hardware_fingerprint,"hardware_fingerprint_mismatch"); T(architecture,"architecture_mismatch"); M(numa_node_count,"numa_node_count_mismatch"); M(page_size,"page_size_mismatch"); T(metric_name,"metric_name_mismatch"); M(metric_version,"metric_version_mismatch"); T(metric_unit,"metric_unit_mismatch"); M(worker_count,"worker_count_mismatch"); M(memory_mb,"memory_mb_mismatch"); M(placement_mode,"placement_mode_mismatch"); T(benchmark_definition_version,"benchmark_definition_version_mismatch"); T(intensity_profile_version,"intensity_profile_version_mismatch"); M(low_intensity_percent,"low_intensity_percent_mismatch"); M(mid_intensity_percent,"mid_intensity_percent_mismatch"); M(high_intensity_percent,"high_intensity_percent_mismatch"); M(numa_balancing_state,"numa_balancing_state_mismatch"); M(window_interval_count,"window_interval_count_mismatch"); M(minimum_worker_run_units,"minimum_worker_run_units_mismatch"); M(benchmark_seed,"benchmark_seed_mismatch");
#undef M
#undef T
    reason(out,n,"match"); return true;
}
static bool valid_row(const P5ThreadActivityContext *c, const char *id, const P5ThreadActivityRawSample *s) { double r; return s->schema_version == P5_THREAD_ACTIVITY_SCHEMA_VERSION && same(s->calibration_id,id) && profile(s->controlled_profile) && s->sample_kind >= P5_THREAD_ACTIVITY_SAMPLE_WARMUP_RUN && s->sample_kind <= P5_THREAD_ACTIVITY_SAMPLE_MEASURED_INTERVAL && s->worker_index < c->worker_count && s->intensity_percent == intensity(c,s->controlled_profile) && s->placement_mode == c->placement_mode && s->worker_count == c->worker_count && s->memory_mb == c->memory_mb && same(s->metric_name,c->metric_name) && s->metric_version == c->metric_version && same(s->metric_unit,c->metric_unit) && s->interval_ms && isfinite(s->load_rate_ops_per_ms) && p5_thread_activity_rate(s->load_operations_delta,s->interval_ms,&r) && r == s->load_rate_ops_per_ms; }
static P5ThreadActivityProfileReport *report(P5ThreadActivityCalibration *c, P5ThreadActivityProfile p) { return p == P5_THREAD_ACTIVITY_PROFILE_LOW ? &c->low : p == P5_THREAD_ACTIVITY_PROFILE_MID ? &c->mid : &c->high; }
static bool same_group(const P5ThreadActivityRawSample *a, const P5ThreadActivityRawSample *b) { return a->run_index == b->run_index && a->worker_index == b->worker_index && a->controlled_profile == b->controlled_profile; }
static void reports(unit_t *u, size_t n, P5ThreadActivityProfileReport *r) { double *v = calloc(n,sizeof(*v)); if (v == NULL) return; for(size_t i=0;i<n;i++)v[i]=u[i].value; statistics(v,n,&r->statistics); free(v); for(size_t i=0;i<n;i++) for(size_t j=i+1;j<n;j++) if(u[i].run==u[j].run && u[i].worker==0 && u[j].worker==1) { double d=(fabs(u[i].value)+fabs(u[j].value))/2.0; if(d>0){double q=fabs(u[i].value-u[j].value)/d; r->worker_agreement_count++; r->worker_agreement_mean+=q; if(q>r->worker_agreement_max)r->worker_agreement_max=q;} } if(r->worker_agreement_count)r->worker_agreement_mean/=r->worker_agreement_count; for(size_t i=0;i<n;i++){ bool first=true; for(size_t j=0;j<i;j++)if(u[j].run==u[i].run)first=false; if(!first)continue; size_t keep=0, omit=0; for(size_t j=0;j<n;j++)if(u[j].run==u[i].run)omit++;else keep++; if(!keep)continue; double *x=calloc(keep,sizeof(*x)); if(!x)continue; size_t k=0;for(size_t j=0;j<n;j++)if(u[j].run!=u[i].run)x[k++]=u[j].value; qsort(x,keep,sizeof(*x),compare_double); double lo=percentile(x,keep,.1),hi=percentile(x,keep,.9);for(size_t j=0;j<n;j++)if(u[j].run==u[i].run){r->leave_one_run_out_total++;if(u[j].value>=lo&&u[j].value<=hi)r->leave_one_run_out_in_band++;}free(x);} if(r->leave_one_run_out_total)r->leave_one_run_out_fraction=(double)r->leave_one_run_out_in_band/r->leave_one_run_out_total; }
int p5_thread_activity_calibration_build(const P5ThreadActivityContext *c,const char *id,const P5ThreadActivityRawSample *samples,size_t count,P5ThreadActivityCalibration *cal,char *out,size_t n) {
    unit_t *units=NULL; size_t unit_count=0, unit_cap=0; if(cal==NULL||samples==NULL||!count||!context_shape(c)||!text(id)){if(cal)cal->status=P5_THREAD_ACTIVITY_CALIBRATION_INVALID_CONTEXT;reason(out,n,"invalid_context");return -1;} memset(cal,0,sizeof(*cal));cal->context=*c;snprintf(cal->calibration_id,sizeof(cal->calibration_id),"%s",id);
    for(size_t i=0;i<count;i++){if(!valid_row(c,id,&samples[i]))goto malformed;for(size_t j=0;j<i;j++)if(samples[j].run_index==samples[i].run_index&&samples[j].worker_index==samples[i].worker_index&&samples[j].sample_index==samples[i].sample_index)goto malformed;}
    for(size_t base=0;base<count;base++){ const P5ThreadActivityRawSample *seed=&samples[base]; bool seen=false; for(size_t i=0;i<base;i++)if(same_group(seed,&samples[i]))seen=true; if(seen)continue; size_t group_count=0; for(size_t i=0;i<count;i++)if(same_group(seed,&samples[i]))group_count++; P5ThreadActivityRawSample *g=calloc(group_count,sizeof(*g)); if(!g)goto malformed; size_t q=0;for(size_t i=0;i<count;i++)if(same_group(seed,&samples[i]))g[q++]=samples[i];qsort(g,group_count,sizeof(*g),compare_sample); size_t max_windows=group_count/P5_THREAD_ACTIVITY_WINDOW_INTERVALS, window_count=0, interval_count=0; bool warm=false; uint64_t next_sample_index=0; double interval_rates[P5_THREAD_ACTIVITY_WINDOW_INTERVALS]; double *window_medians=max_windows?calloc(max_windows,sizeof(*window_medians)):NULL; if(max_windows&&!window_medians){free(g);goto malformed;} for(size_t i=0;i<group_count;i++){if(g[i].sample_kind==P5_THREAD_ACTIVITY_SAMPLE_WARMUP_RUN){warm=true;break;}if(g[i].sample_kind!=P5_THREAD_ACTIVITY_SAMPLE_MEASURED_INTERVAL||!g[i].valid){interval_count=0;continue;}if(interval_count&&g[i].sample_index!=next_sample_index)interval_count=0;interval_rates[interval_count++]=g[i].load_rate_ops_per_ms;next_sample_index=g[i].sample_index+1;if(interval_count==P5_THREAD_ACTIVITY_WINDOW_INTERVALS){qsort(interval_rates,interval_count,sizeof(*interval_rates),compare_double);window_medians[window_count++]=percentile(interval_rates,interval_count,.5);interval_count=0;}} if(!warm&&window_count){if(unit_count==unit_cap){size_t nc=unit_cap?unit_cap*2:16;unit_t *z=realloc(units,nc*sizeof(*z));if(!z){free(window_medians);free(g);goto malformed;}units=z;unit_cap=nc;}qsort(window_medians,window_count,sizeof(*window_medians),compare_double);units[unit_count++]=(unit_t){seed->run_index,seed->worker_index,seed->controlled_profile,percentile(window_medians,window_count,.5),window_count};} free(window_medians);free(g); }
    for(int p=0;p<3;p++){P5ThreadActivityProfile current=(P5ThreadActivityProfile)p;size_t k=0;for(size_t i=0;i<unit_count;i++)if(units[i].profile==current)k++;P5ThreadActivityProfileReport *r=report(cal,current);r->worker_run_count=k;for(size_t i=0;i<unit_count;i++)if(units[i].profile==current)r->window_count+=units[i].windows;if(k<c->minimum_worker_run_units){cal->status=P5_THREAD_ACTIVITY_CALIBRATION_INSUFFICIENT_SAMPLES;reason(out,n,"worker_run_units_required");free(units);return 0;}unit_t *x=calloc(k,sizeof(*x));if(!x)goto malformed;size_t z=0;for(size_t i=0;i<unit_count;i++)if(units[i].profile==current)x[z++]=units[i];reports(x,k,r);free(x);} cal->low.gap_ratio_available=cal->low.statistics.p90>0;cal->mid.gap_ratio_available=cal->mid.statistics.p90>0;if(cal->low.gap_ratio_available)cal->low.gap_ratio=(cal->mid.statistics.p10-cal->low.statistics.p90)/cal->low.statistics.p90;if(cal->mid.gap_ratio_available)cal->mid.gap_ratio=(cal->high.statistics.p10-cal->mid.statistics.p90)/cal->mid.statistics.p90;cal->status=cal->low.statistics.p90<cal->mid.statistics.p10&&cal->mid.statistics.p90<cal->high.statistics.p10?P5_THREAD_ACTIVITY_CALIBRATION_VALID:P5_THREAD_ACTIVITY_CALIBRATION_NOT_SEPARABLE;reason(out,n,p5_thread_activity_calibration_status_name(cal->status));free(units);return 0;
malformed: free(units);cal->status=P5_THREAD_ACTIVITY_CALIBRATION_MALFORMED;reason(out,n,"malformed_sample");return -1;
}
P5ThreadActivityClass p5_thread_activity_classify_window_rate(const P5ThreadActivityCalibration *c,double r){if(c==NULL||c->status!=P5_THREAD_ACTIVITY_CALIBRATION_VALID||!isfinite(r))return P5_THREAD_ACTIVITY_UNAVAILABLE;if(r>=c->low.statistics.p10&&r<=c->low.statistics.p90)return P5_THREAD_ACTIVITY_COLD;if(r>=c->mid.statistics.p10&&r<=c->mid.statistics.p90)return P5_THREAD_ACTIVITY_MODERATE;if(r>=c->high.statistics.p10&&r<=c->high.statistics.p90)return P5_THREAD_ACTIVITY_HOT;return P5_THREAD_ACTIVITY_UNAVAILABLE;}
